### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by ninelore** [death7654/Chrultrabook-Controller#20]
Currently only spams log when something is missing. 

Pop error messages instead of log spam and force-closing

**Comment by death7654** [comment]
What os?

**Comment by ninelore** [comment]
any
------- Original Message -------

**Comment by death7654** [comment]
I dont get this error, when does it happen? Is it on build?

**Comment by ninelore** [comment]
Issue persists

**Comment by ninelore** [comment]
![image](https://github.com/death7654/Chrultrabook-Controller/assets/21343557/26ec94a4-a3d1-4f08-a352-6d4cdfe5e3a3)

**Comment by death7654** [comment]
Are you running in a chrultrabook?

**Comment by death7654** [comment]
The missing ectools is the driver that coolstar provides for chrultrabook

**Comment by death7654** [comment]
I am quite stupid, ill figure out a way to have an error msg

**Comment by death7654** [comment]
Im sorry for taking this long, it has been completed
It works on my computer currently

**Comment by ninelore** [comment]
App is still spamming commands

**Comment by death7654** [comment]
> App is still spamming commands
> 
> It should stop trying if it cant find the executables

I dont think that is possible since it runs the applicaiton every second

**Comment by death7654** [comment]
added :)
