### ISSUE TITLE
Automatically Detect Dark Mode

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [death7654/Chrultrabook-Controller#30]

**Comment by death7654** [comment]
it automatically detects it

**Comment by ChocolateLoverRaj** [comment]
I was on dark mode in windows and it opened in light mode.

**Comment by death7654** [comment]
Dark mode on windows does not correlate with dark mode on the app

**Comment by death7654** [comment]
Also, an apology i read the issue wrong

**Comment by ChocolateLoverRaj** [comment]
So I made this issue requesting that this app opens in dark mode if it is running in windows and the user has dark mode in windows.

**Comment by death7654** [comment]
I would like to keep windows and the app seperate
