### ISSUE TITLE
dell activity light

### ISSUE THREAD

**Issue by WeirdTreeThing** [death7654/Chrultrabook-Controller#36]
most important feature ever. candy and kefka users will finally be able to use their fancy light!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by death7654** [comment]
red, green, blue, white, cyan, magenta, yellow, black

**Comment by ChocolateLoverRaj** [comment]
I'm curious, can u send a picture of what the light looks like?

**Comment by WeirdTreeThing** [comment]
![image](https://github.com/death7654/Chrultrabook-Controller/assets/46109425/ab90ce31-e8ed-45a5-8041-6adcf39840ac)

**Comment by ChocolateLoverRaj** [comment]
That's very cool. Is it RGB?

**Comment by WeirdTreeThing** [comment]
> red, green, blue, white, cyan, magenta, yellow, black
no

**Comment by death7654** [comment]
its done. WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO, YEAH BABYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
