### ISSUE TITLE
App not working at most

### ISSUE THREAD

**Issue by Melelysum** [death7654/Chrultrabook-Controller#37]
Error `No such file or directory (os error 2)`
The app launches and tells me my configuration, but apart from RAM usage I can't see or modify anything
I'm running Arch Linux kernel 6.5.5-arch1-1 on a Intel© Core™ i5-10210U CPU @ 1.60GHz × 4 with 8Gb of RAM 
My chromebook is a helios    asus C436FA

**Comment by death7654** [comment]
How do you get that error?, is it possible for you to ping me and show me in the chrultrabook server? im death7654

**Comment by death7654** [comment]
Is it possible for you to show a picture of the error?

**Comment by Melelysum** [comment]
![Capture d’écran du 2023-10-03 07-55-48](https://github.com/death7654/Chrultrabook-Controller/assets/93212327/68c0e943-a34d-4c46-80ad-a5dd25eaf55d)
![Capture d’écran du 2023-10-03 08-01-11](https://github.com/death7654/Chrultrabook-Controller/assets/93212327/35e61e96-87a0-4648-a4c5-cfee549ff900)
![Capture d’écran du 2023-10-03 08-01-22](https://github.com/death7654/Chrultrabook-Controller/assets/93212327/94e5a575-2ae2-4c09-a7b7-61711450953b)
![Capture d’écran du 2023-10-03 08-01-33](https://github.com/death7654/Chrultrabook-Controller/assets/93212327/600f89fd-94ab-4dbb-b47f-dc4a5e5b429b)
![Capture d’écran du 2023-10-03 08-01-40](https://github.com/death7654/Chrultrabook-Controller/assets/93212327/6b77c22c-50a3-4d6b-8d4d-702a9c2c5290)


here is what i get when launching through a terminal (the same happens when launching not from a terminal
A slight other issue as you can see in the last 2 pictures the buttons are not visible when the side menu is open

**Comment by death7654** [comment]
It will be fixed in the 2.4.1 update, I forgot to take some things out

System Controls is meant to be empty for now, due to your chromebook not having any backlight. In the future it will have keyboard remap so it will not be empty anymore :)

**Comment by Melelysum** [comment]
So the system controls and cpu sensors will be fixed in the next update ?
Also I do have a backlight ? I can power it up and down from 5% to a 100% 5% by 5% using the power managment tool (and applet or spices) in cinnamon.

**Comment by death7654** [comment]
the backlight is the keyboard backlight, not the display backlight

**Comment by Melelysum** [comment]
Ok but I have both of them
I just see that I don't have any fan control is it supposed to be like that ? 
I know I have a fan because when I opened the chromebook to flash coreboot I saw it and sometimes I hear the fan powering up

**Comment by death7654** [comment]
can you post the output of 

ectool pwmgetkblight

and 

ectool pwmgetfanrpm

**Comment by Melelysum** [comment]
here is the result for the first command, previously setting the backlight to 60% then to 0% and sending the command again :
```
[melelysum@melelysum-helios-notebook ~]$ sudo ectool pwmgetkblight
Current keyboard backlight percent: 60
[melelysum@melelysum-helios-notebook ~]$ sudo ectool pwmgetkblight
Current keyboard backlight percent: 0
```

And here is the result of the second command :
```
[melelysum@melelysum-helios-notebook ~]$ sudo ectool pwmgetfanrpm
Fan 0 RPM: 0
```
I don't think the fan is running rn so it seem to be alright

**Comment by death7654** [comment]
I think I have to optimize my checks

**Comment by death7654** [comment]
Ok, so I do not think that it is an error on my part but rather an error on how GitHub actions compiles. Ill try native compilations, as it seems to work better than actions

**Comment by death7654** [comment]
Ill get a test build for linux ready today and you can test it

**Comment by Melelysum** [comment]
I will, I'm Melelysum on the discord if you prefer to talk on discord rather than here

**Comment by death7654** [comment]
That would be so much easier, please ping me, im death7654

**Comment by death7654** [comment]
check the latest release, I do apologize for any inconvience I may have caused
