### ISSUE TITLE
Fan control still missing on linux after update

### ISSUE THREAD

**Issue by Melelysum** [death7654/Chrultrabook-Controller#38]
Fan control missing on arch linux 6.5.5-arch1-1
also no info is get when using the button to get them in Memory diagnostics
I tried every choice available in the drop down menu, nothing.
My laptop is a asus chromebook flip C436FA CometLake-U codenamed Helios

**Comment by death7654** [comment]
This seems like a packaging error

[https://tree123.org/chrultrabook/utils/ectool](url)
[https://tree123.org/chrultrabook/utils/cbmem](url)

download these binaries and place them in /usr/bin

Then CD to the location

`sudo chmod u+s ectool && sudo chmod u+s cbmem`

It should have been packaged in the appimage, and I do not know what went wrong.

**Comment by WeirdTreeThing** [comment]
Do not put those in /usr/bin

**Comment by Melelysum** [comment]
they already were there
