### ISSUE TITLE
Stop interval when app is not focused/or when page is hidden (except Fan curves)

### ISSUE THREAD

**Issue by death7654** [death7654/Chrultrabook-Controller#50]

**Comment by death7654** [comment]
lowers battery usage gives/frees up resources

**Comment by ethanaobrien** [comment]
I dont think the interval should completely stop. Slowing it down to run less frequently is a good idea

**Comment by death7654** [comment]
> I dont think the interval should completely stop. Slowing it down to run less frequently is a good idea

its just cpu usage, and ram percentage, since cpu temps are necessary

**Comment by ethanaobrien** [comment]
Might look a little dirty switching back if we permanently stop them. Changing to like 5-10 seconds is a good idea

**Comment by death7654** [comment]
it'll start back up when the window is focused

**Comment by death7654** [comment]
done
